name: LibreBuild
version: '1.1.1'
main: net.ezplace.librebuild.LibreBuild
api-version: '1.20'
softdepend: [WorldEdit, WorldGuard]
author: andrewYerNau, TheArmagan
commands:
  librebuild:
    aliases: [lb]
    usage: "/librebuild help for more information"
permissions:
  librebuild.item.use:
    default: true
  librebuild.command.admin:
    default: op